# Site settings
title: HS Hackers NYC
email: "hello at victorlourng dot com (CHANGE ME!)"
description: "Welcome to the High School Hackers NYC meetup group!"
baseurl: ""
url: "http://nyc.hshackers.org"

# Build settings
markdown: kramdown
permalink: pretty
